name: metrics
on:
  schedule:
    cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, community, repositories, metadata
          repositories_forks: yes
          token: ${{ secrets.GITHUB_TOKEN }}
          user: patrick-choe
          template: classic
          config_timezone: Asia/Seoul
          config_twemoji: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 0

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes

          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_contributors_sections: yes

          plugin_stars: yes
          plugin_stars_limit: 10

          plugin_topics: yes
          plugin_topics_limit: 0

          plugin_reactions: yes
          plugin_reactions_limit: 300
          plugin_reactions_limit_issues: 200
          plugin_reactions_days: 0

          plugin_followup: yes

          plugin_lines: yes

          plugin_traffic: yes

          plugin_stargazers: yes

          plugin_projects: yes
          plugin_projects_limit: 10
          plugin_projects_descriptions: yes

          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          plugin_discussions: yes

          plugin_support: yes

          plugin_notable: yes
          plugin_notable_repositories: yes

          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1.0
